import SplashView from '@/sections/splash/view/splash-view';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'منو آنلاین',
  description: 'Generated by create next app',
};

export default function Home() {
  return <SplashView />;
}
