name: Nextjs CI/CD
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x to Build
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
        run: |
          cd /var/www/html/dashboard
          git pull
          npm install
          npm run prisma generate
          npm run build
          pm2 restart all
        env:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
