name: CI/CD with GitHub Actions

on:
  push:
    branches:
      - main # اگر شاخه اصلی پروژه تغییر کرد، این CI/CD اجرا می‌شود.

jobs:
  build:
    runs-on: ubuntu-latest # اجرای job روی یک سرور اوبونتو

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # استفاده از اکشن برای checkout کردن کد از مخزن

      - name: Deploy to Server
        run: |
          ssh root@193.151.154.154 
          S2@8mpuUP3#*
          'cd /var/www/html/dashboard && git pull origin main && npm install && npm run build && pm2 restart all'
        env:
          SERVER_SSH_USER: root
          SERVER_SSH_PASSWORD: ${{ secrets.PASSWORD }}
